// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Card struct {
	Uid      string
	UserName string
}

type Log struct {
	ID        int32
	Uid       string
	Permitted bool
	Time      time.Time
}
