// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"
)

const authorizedCard = `-- name: AuthorizedCard :one
SELECT user_name FROM card
WHERE uid = ? LIMIT 1
`

func (q *Queries) AuthorizedCard(ctx context.Context, uid string) (string, error) {
	row := q.db.QueryRowContext(ctx, authorizedCard, uid)
	var user_name string
	err := row.Scan(&user_name)
	return user_name, err
}
